[project]
name = "vktools"
version = "1.0.0"
description = "dump things"
authors = ["nt"]
readme = "README.md"

requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "cryptography>=44.0.2",
    "ffmpeg-python>=0.2.0",
    "loguru>=0.7.3",
    "pillow>=11.1.0",
    "requests>=2.32.3",
    "vk-api>=11.9.9",
]
